normal:
  target_class: 0
  number: 2000
  num_red: [2, 2]
  num_green: [2, 2]
  signal_size: [1, 2]
  target_class: 0

amp:
  target_class: 0
  number: 200
  num_red: [2, 2]
  num_green: [8, 15]
  signal_size: [1, 2]
  target_class: 1

# green_loss:
#   target_class: 1
#   number: 1000
#   num_red: [2, 2]
#   num_green: [1, 1]
#   signal_size: [1, 2]

# green_gain:
#   target_class: 2
#   number: 1000
#   num_red: [2, 2]
#   num_green: [2, 20]
#   signal_size: [1, 2]